### ISSUE TITLE
Incorrect handling of relative links in readme

### ISSUE THREAD

**Issue by dakujem** [componette/componette#104]
Relative links within readme **markdown files** are not being handled well.

**Problem**
- all the relative links pointing to other files within the repository are generated with a redundant space " " character preceding the relative link part
- as a result, users clicking the links get 404 error on github

**Example**

| What | Value |
|---|---|
| realtive link in markdwon source | `examples/ajax/ExamplePresenter.php` | 
| current incorrectly generated absolute link | `https://github.com/dakujem/selectoo/blob/master /examples/ajax/ExamplePresenter.php` |
| desired correct absolute link | `https://github.com/dakujem/selectoo/blob/master/examples/ajax/ExamplePresenter.php` |

> Note the space character in the `blob/master /examples` part of the generated URL

**Link to where this issue can be observed:**
https://componette.com/dakujem/selectoo/

**Comment by f3l1x** [comment]
Thanks. Do mind to resolve this bug?

**Comment by dakujem** [comment]
So I found the bug and fixed it using the web interface. Haven't tested it, but it is obviously a typo-bug.

**Comment by f3l1x** [comment]
Thank you.

**Comment by dakujem** [comment]
No problem.
