### ISSUE TITLE
Releases are not shown

### ISSUE THREAD

**Issue by dakujem** [componette/componette#106]
I believe the "Releases" tab does not show the releases from github. This is true for many of the packages.

It might not be a bug though - I might have overlooked some logic inside Componette that only filters some releases (but I was unable to guess what the rules were).

**Comment by f3l1x** [comment]
Hey, what package do you mean? I'll check it.

**Comment by dakujem** [comment]
Well, I noticed this with my package, but there are other:
- [dakujem/selectoo](https://componette.com/dakujem/selectoo/)
- [kdyby/requeststack](https://componette.com/kdyby/requeststack/)
- [h4kuna/fio](https://componette.com/h4kuna/fio/)

I don't see a pattern why some do and other do not have any releases listed within the componette app. I checked the github API and the releases are correctly returned.

**Comment by f3l1x** [comment]
I see it now. It's now a bug is a feature.

The package (https://github.com/h4kuna/fio/releases) has not any real realeses notes, there're just a tags. 

I think we could include tags to releases on componette also.

**Comment by dakujem** [comment]
Hmm, but the package dakujem/selectoo DOES have releases... So does kdyby/requeststack. 
You can find more packages like this, I just did not want to waste time searching for them.

**Comment by f3l1x** [comment]
150 releases synchronized, I owe you :beer: .

**Comment by f3l1x** [comment]
I've changed collation of column.

```
ALTER TABLE `github_release`
CHANGE `name` `name` varchar(255) COLLATE 'utf8mb4_general_ci' NOT NULL AFTER `gid`;
```

**Comment by dakujem** [comment]
I believe this has now been solved. Thanks! Let me close the issue.
