### ISSUE TITLE
Error 500 - search

### ISSUE THREAD

**Issue by JanGalek** [componette/componette#107]
Hi, I was trying found my fresh added "addon" and I got error 500 

![image](https://user-images.githubusercontent.com/13171542/38548447-21662606-3cb2-11e8-81a7-df580f357b5d.png)

If you want, I will try fix this, but I will need error ;)

**Comment by f3l1x** [comment]
Hi. I will take a look. Thank you. :-)

**Comment by JanGalek** [comment]
Maybe, you will help info, that do when,

I try search some addon, result doesn't exists, after I add addon and try search again.
