### ISSUE TITLE
RSS feed & OpenSearch URLs returning 404

### ISSUE THREAD

**Issue by Gappa** [componette/componette#110]
Both of these URLs now return 404:

- https://componette.com/rss/latest.xml
- https://componette.com/opensearch.xml?v=2.4

The RSS feed stopped working propably two/three weeks ago - guessing from the "Latest added" on the website, but I might be way off.

Regarding the OpenSearch URL I don't  really know, but when trying the RSS URL I tried it too and it wasn't working as well.

**Comment by JanTvrdik** [comment]
Probably caused by https://github.com/componette/componette/blob/master/.docker/app/Caddyfile#L7

**Comment by f3l1x** [comment]
Thank you. Should be fixed.
