### ISSUE TITLE
[idea] emoticons

### ISSUE THREAD

**Issue by f3l1x** [componette/componette#68]
It would be nice to have emoticons in addon title / description.

https://componette.com/achse/nette-date-time-input/

**Comment by f3l1x** [comment]
It's getting more needed that I thought.

![addons__plugins_and_components___componette](https://cloud.githubusercontent.com/assets/538058/25520811/9c1828de-2bfd-11e7-9a77-c1ef3e8dd0b6.png)

**Comment by f3l1x** [comment]
![selection_020](https://user-images.githubusercontent.com/538058/27012426-d50beb54-4ecf-11e7-8e5e-8cba6ff88eb7.png)

**Comment by lukasneubauer** [comment]
great, i like this :+1:
