### ISSUE TITLE
Deprecated addons

### ISSUE THREAD

**Issue by enumag** [componette/componette#74]
Some addons get deprecated over time. This might be possible to detect from packagist - such addons are marked as abandoned with an optional replacement suggestion.

**Comment by f3l1x** [comment]
Thanks for an idea. At this time, this addon is marked as ARCHIVED, so it cannot be found anymore. It's a simplest solution I know. 

But maybe in the future. It's a useful.

**Comment by f3l1x** [comment]
This is also implemented. Package is not shown anymore.
