### ISSUE TITLE
[QA] add phpstan

### ISSUE THREAD

**Issue by f3l1x** [componette/componette#83]
Configuration in the README (https://github.com/phpstan/phpstan).

-----

cc @ondrejmirtes

**Comment by ondrejmirtes** [comment]
@f3l1x I can prepare a PR if you'd like me to.

**Comment by f3l1x** [comment]
@ondrejmirtes Thanks a lot, but it not nescessary. I would like to go throw the readme and handle possible breakpoints by my self. I can provide some feedback after that. 

Thank you for your jof on @phpstan. It looks like a great missing tool for PHP world. :+1:

**Comment by ondrejmirtes** [comment]
@f3l1x OK, just show me the integration before merging so I can give my 2 cents on it :)

**Comment by f3l1x** [comment]
@ondrejmirtes I've finally integrated it. :-) Good job btw, phpstan's hits are pretty useful and I didn't get lost. 

I would be happy if you could take a look.

**Comment by ondrejmirtes** [comment]
@f3l1x Cool, it's nice :) 👍 Are you still extending Nette\Object for BC reasons?

**Comment by f3l1x** [comment]
@ondrejmirtes Well, I do not, but nextras/orm does, so I cannot avoid it.
