### ISSUE TITLE
Repository - rename to componette/componette

### ISSUE THREAD

**Issue by f3l1x** [componette/componette#89]
I would like to rename repository to more appropriate name `componette/componette`.

There's big chance in the future, that we'll have for example `componette.org` domain or any other.

Do you agree?

@chemix @matej21

**Comment by chemix** [comment]
I'm fine with this

**Comment by f3l1x** [comment]
Thank you guys @chemix @milo and @mrtnzlml

**Comment by f3l1x** [comment]
Done
