### ISSUE TITLE
CSS: remove red background for tabulators

### ISSUE THREAD

**Issue by milo** [componette/componette#90]
For example here: https://componette.com/milo/vendor-versions/

It is the same as on GitHub. But I think it is not nice :)

**Comment by f3l1x** [comment]
I keep on eye on it. :-)

**Comment by f3l1x** [comment]
@milo 
![selection_019](https://user-images.githubusercontent.com/538058/27011645-79feab02-4ec0-11e7-87b9-7218b8ce123b.png)
