### ISSUE TITLE
Design proposal in addon detail

### ISSUE THREAD

**Issue by paveljanda** [componette/componette#96]
I think it would be cool to:

1, Make the `border-radius` in readme code of value `1px` instead of `6px`
2, Make the conf.neon code `font-weight` `normal` instead of `bold`
3, Make the `pre` code loose the the border..

It is 21. century after all :P

## Before:

<img width="1920" alt="screen shot 2017-07-17 at 11 05 39" src="https://user-images.githubusercontent.com/1488874/28261517-ec50a328-6adf-11e7-8029-973f2f25face.png">

## After:

<img width="1920" alt="screen shot 2017-07-17 at 11 01 08" src="https://user-images.githubusercontent.com/1488874/28261521-f206e368-6adf-11e7-8abe-bea7132fa373.png">

**Comment by f3l1x** [comment]
It looks great ;-)

**Comment by paveljanda** [comment]
Cool, I will send a PR
