### ISSUE TITLE
Design proposal in componette footer: author's avatar resolution

### ISSUE THREAD

**Issue by paveljanda** [componette/componette#97]
Since people have great resolution on their desktops, can we make also the resolution bigger in these avatars?

<img width="1920" alt="screen shot 2017-07-17 at 10 59 21" src="https://user-images.githubusercontent.com/1488874/28261619-411c4b5a-6ae0-11e7-94a7-2df0bc8db626.png">

**Comment by f3l1x** [comment]
What do you suggest? Please, don't forget about 1024px resoluition ;-)

**Comment by paveljanda** [comment]
I suggest make the resolution of each avatar twice as big (not the size! - the resolution). Don't you see the how blurry it is on the given screenshot? :)

**Comment by f3l1x** [comment]
Oh, I get it. Well, there's a blur effect on images. Should I drop it? xD

**Comment by paveljanda** [comment]
Aha! Oh boy. :D Yes.

**Comment by hrach** [comment]
I dont line the blur (either) 😀😉
